[build]
  functions = "netlify/functions"
  publish = "dist"
  base = "/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*.(jpg|png|gif|svg)"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
